### ISSUE TITLE
Oct 28 Tech Salon

### ISSUE THREAD

**Issue by danielglh** [strikingly/tech-salon#7]
Topic: Typescript

Speaker: Andrew Bethel(@abeth86), Strikingly Frontend Engineer

Summary: Typescript is a superset of javascript, and brings strong typing to an otherwise very open language.  This sharing will go over the features included in TS, the advantages brought from strong typing and more direct debugging, as well as provide examples of how it works with libraries like React.

**Comment by abeth86** [comment]
Topic: Typescript

Summary: Typescript is a superset of javascript, and brings strong typing to an otherwise very open language.  This sharing will go over the features included in TS, the advantages brought from strong typing and more direct debugging, as well as provide examples of how it works with libraries like React.

**Comment by dfguo** [comment]
@abeth86 can you also add a comparison with other solutions (like Flow) addressing the same problem?

**Comment by ghost** [comment]
Definitely!
